In [2]:
import pandas as pd
import numpy as np
obj=pd.Series([4.5,7.2,-5.3,3.6], index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [3]:
obj2=obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [4]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [5]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [6]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohid','Texas','California'])
frame


Ohid  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [7]:
frame2=frame.reindex(['a','b','c','d'])
frame2

Ohid  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [8]:
frame3=frame2.reindex(columns=['Texas','Utah','California'])
frame3

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [9]:
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])
new_obj=obj.drop(['c','d'])
new_obj

a    0.0
b    1.0
e    4.0
dtype: float64

In [10]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [11]:
data.drop(['Colorado','Ohio'],inplace=True)
data.drop(['two','four'],axis=1)

one  three
Utah        8     10
New York   12     14

In [12]:
obj=pd.Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [13]:
obj['b']
obj[1]
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [14]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [15]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [16]:
data=pd.DataFrame(np.arange(16).reshape(4,4),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [17]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [18]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [19]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [20]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [21]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [22]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [23]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [24]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [25]:
df1.add(df2,fill_value=0.0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [26]:
arr=np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [27]:
arr[0]

array([0., 1., 2., 3.])

In [28]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [29]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregen'])
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregen  9  10  11

In [30]:
sereis=frame.iloc[0]
sereis

b    0
d    1
e    2
Name: Utah, dtype: int64

In [31]:
frame-sereis

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregen  9  9  9

In [32]:
frame.sub(sereis,axis=1)

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregen  9  9  9

In [33]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame
np.abs(frame)

b         d         e
Utah    0.182847  0.631724  0.419759
Ohio    0.237858  1.434893  0.502346
Texas   0.451408  2.329528  0.876926
Oregon  0.491698  1.305910  0.954156

In [34]:
f=lambda x:x.max()-x.min()
frame.apply(f)

b    0.308851
d    2.961251
e    1.456502
dtype: float64

In [35]:
frame.apply(f,axis='columns')

Utah      0.814570
Ohio      1.937239
Texas     1.878119
Oregon    0.814212
dtype: float64

In [36]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])
frame.apply(f)

b         d         e
min  0.182847 -0.631724 -0.502346
max  0.491698  2.329528  0.954156

In [39]:
format_=lambda x:'%.2f'%x
frame.applymap(format_)

b      d      e
Utah    0.18  -0.63  -0.42
Ohio    0.24   1.43  -0.50
Texas   0.45   2.33   0.88
Oregon  0.49   1.31   0.95

In [42]:
obj=pd.Series(range(4),index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [49]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],
                  columns=['d','a','b','c'])
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [54]:
obj=pd.Series([4,np.nan,7,np.nan,-3,2])
obj.sort_values()

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [59]:
frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [62]:
obj=pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [64]:
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [65]:
obj=pd.Series(range(5),index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [66]:
obj.index.is_unique

False

In [67]:
obj['a']

a    0
a    1
dtype: int64

In [68]:
obj['c']

4

In [74]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [75]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [76]:
df.mean(axis=1,skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [79]:
df.idxmax()

one    b
two    d
dtype: object

In [80]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [81]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [98]:
pip install --upgrade pandas-datareader

Note: you may need to restart the kernel to use updated packages.


In [108]:
import pandas_datareader as web

all_data={ticker: web.get_data_yahoo(ticker)
         for ticker in ['AAPL','IBM','MSFT','GOOG']}
all_data

In [109]:
price = pd.read_pickle("Practice/yahoo_price.pkl")
volume = pd.read_pickle("Practice/yahoo_volume.pkl")


AAPL        GOOG         IBM       MSFT
Date                                                     
2010-01-04   27.990226  313.062468  113.304536  25.884104
2010-01-05   28.038618  311.683844  111.935822  25.892466
2010-01-06   27.592626  303.826685  111.208683  25.733566
2010-01-07   27.541619  296.753749  110.823732  25.465944
2010-01-08   27.724725  300.709808  111.935822  25.641571
...                ...         ...         ...        ...
2016-10-17  117.550003  779.960022  154.770004  57.220001
2016-10-18  117.470001  795.260010  150.720001  57.660000
2016-10-19  117.120003  801.500000  151.259995  57.529999
2016-10-20  117.059998  796.969971  151.520004  57.250000
2016-10-21  116.599998  799.369995  149.630005  59.660000

[1714 rows x 4 columns]

In [110]:
returns=price.pct_change()
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [112]:
returns.MSFT.corr(returns.IBM)
returns.MSFT.cov(returns.IBM)


8.870655479703546e-05

In [113]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [114]:
returns.corrwith(returns.IBM)

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [115]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [116]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [117]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [121]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [126]:
mask=obj.isin(['c','b'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [125]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [128]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                     "Qu2": [2, 3, 1, 2, 3],
                     "Qu3": [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [135]:
results=data.apply(pd.value_counts).fillna(0.0)
results

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0