## ufunc 라고 불리기도 하는 유니버설 함수는 ndarray 안에 있는 데이터 원소별로 연산을 수행하는 함수다. 유니버설 함수는 하나 이상의 스칼라 값을 받아서 하나 이상의 스칼라 결과 값을 반환하는 함수이다. 고속으로 수행할 수 있는 벡터화된 래퍼 함수라고 생각하면 된다.
### 래퍼 함수(Wrapper function)는 다른 함수를 감싸고(wrapper) 호출하거나 수정하여 추가 동작을 수행하는 함수를 말한다.

In [2]:

import numpy as np
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 단항 유니버설 함수

In [3]:
np.sqrt(arr) # 제곱근을 계산

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.square(arr) #각 원소의 제곱을 계산 

In [4]:
np.exp(arr) #각 원소의 지수함수(e^x) 계산

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [5]:
np.log(arr) #자연 로그를 계산. log10, log2,log1p 는 각각 로그10,로그2,로그(1+x) 계산

/var/folders/l4/y_bsqjv51cg_wqy5xcj1b3940000gn/T/ipykernel_7397/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [6]:
np.sign(arr) #각 원소의 부호를 계산. 0은 0, 1은 양수, -1은 음수를 의미

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
arr=np.random.randn(8)*4
arr

array([ 6.54374145, -3.42980576, -3.13354923,  3.52547703, -1.8716203 ,
       -0.23389988, -5.13359235, -1.76132344])

In [17]:
np.ceil(arr) # 각 원소의 소수자리를 올린다.


array([ 7., -3., -3.,  4., -1., -0., -5., -1.])

In [19]:
np.floor(arr) #각 원소의 소수자리를 내린다.

array([ 6., -4., -4.,  3., -2., -1., -6., -2.])

In [20]:
np.rint(arr) #각 원소의 소수자리를 반올림한다. dtype은 유지된다

array([ 7., -3., -3.,  4., -2., -0., -5., -2.])

In [21]:
np.modf(arr) #각 원소의 몫과 나머지를 각각의 배열로 반환한다.

(array([ 0.54374145, -0.42980576, -0.13354923,  0.52547703, -0.8716203 ,
        -0.23389988, -0.13359235, -0.76132344]),
 array([ 6., -3., -3.,  3., -1., -0., -5., -1.]))

In [22]:
np.isnan(arr) #각 원소가 숫자가 아닌지를 나타내는 불리언 배열을 반환한다.

array([False, False, False, False, False, False, False, False])

## 이항 유니버설 함수

In [24]:
x=np.random.randn(7)*5
y=np.random.randn(7)*5
x,y

(array([-5.42702991, -1.76745298, -4.48174217, 10.48743983, -2.18265429,
         6.45907653, -3.06613725]),
 array([ 1.18489649, -7.18918909, -2.15816664,  7.85140577,  0.85979612,
         0.06029591,  8.14517696]))

In [25]:
np.add(x,y) #두 배열의 같은 위치의 원소를 더한다.

array([-4.24213342, -8.95664208, -6.63990881, 18.3388456 , -1.32285816,
        6.51937244,  5.07903971])

In [27]:
np.subtract(x,y) #첫번째 배열의 원소에서 두번째 배열의 원소를 뺀다

array([ -6.6119264 ,   5.42173611,  -2.32357552,   2.63603405,
        -3.04245041,   6.39878063, -11.21131421])

In [28]:
np.multiply(x,y) #배열의 원소끼리 곱한다

array([ -6.43046869,  12.70655372,   9.67234644,  82.34114563,
        -1.8766377 ,   0.38945587, -24.97423051])

In [29]:
np.divide(x,y) #첫 번째 배열의 원소를 두 번째 배열의 원소로 나눈다.

array([ -4.58017216,   0.24584873,   2.07664324,   1.33574039,
        -2.53857191, 107.12297176,  -0.37643593])

In [30]:
np.power(x,y)#첫번째 배열을 두 번째 배열의 원소만큼 제곱한다.

/var/folders/l4/y_bsqjv51cg_wqy5xcj1b3940000gn/T/ipykernel_7397/596891162.py:1: RuntimeWarning: invalid value encountered in power
  np.power(x,y)#첫번째 배열을 두 번째 배열의 원소만큼 제곱한다.


array([           nan,            nan,            nan, 1.03202511e+08,
                  nan, 1.11905121e+00,            nan])

In [31]:
np.maximum(x,y)#각 배열의 두 원소 중 큰 값을 반환한다.

array([ 1.18489649, -1.76745298, -2.15816664, 10.48743983,  0.85979612,
        6.45907653,  8.14517696])

In [32]:
np.minimum(x,y)#긱 배열의 두 원소 중 작은 값을 반환한다.

array([-5.42702991, -7.18918909, -4.48174217,  7.85140577, -2.18265429,
        0.06029591, -3.06613725])

In [33]:
np.mod(x,y) #첫 번째 배열의 원소를 두 번째 배열의 원소로 나눈 나머지를 구한다

array([ 0.49745254, -1.76745298, -0.16540888,  2.63603405,  0.39673408,
        0.00741469,  5.07903971])

In [34]:
np.copysign(x,y)#첫 번쨰 배열의 원소의 기호를 두 번째 배열의 원소의 기호로 바꾼다


array([ 5.42702991, -1.76745298, -4.48174217, 10.48743983,  2.18265429,
        6.45907653,  3.06613725])

In [35]:
#greater,greater)equal,less,less equal,equal,not_equal
#은 >,>=,<,<=,=,!=의 연산결과를 불리언 배열로 반환한다.
np.greater(x,y)

array([False,  True, False,  True, False,  True, False])

In [38]:
#logical_and =&
#logical_or =|
#logical_xor=^ 의 논리연산 결과를 반환한다.
np.logical_and(x,y)

array([ True,  True,  True,  True,  True,  True,  True])